### ISSUE TITLE
RuntimeError: running_mean should contain 1024 elements not 2048.

### ISSUE THREAD

**Issue by craine** [walkwithfastai/walkwithfastai.github.io#18]
Hi. Posting this over here instead of fastai 👍 
I'm seeing the same exact issue all of the sudden:
RuntimeError: running_mean should contain 1024 elements not 2048.
https://colab.research.google.com/drive/1kY_qH-GCG9IiUhQmH0Gk3-IU338bD0Ea?usp=sharing

Thanks!
Charlie

**Comment by muellerzr** [comment]
This should now be fixed!

**Comment by dreamflasher** [comment]
I installed the latest timm version from pip: "0.3.4", but still receiving this error.

**Comment by muellerzr** [comment]
What are your versions of fastai and wwf? Also can you share a reproducer?

**Comment by dreamflasher** [comment]
```
python3 -c "import fastai; import torch; import fastcore; import timm; print(torch.__version__, fastai.__version__, fastcore.__version__, timm.__version__)" 
1.7.0+cu110 2.2.2 1.3.16 0.3.4
```


```
from wwf.vision.timm import timm_learner

from fastai.vision.all import *


def label_func(f):
    return f[0].isupper()


path = untar_data(URLs.PETS)
files = get_image_files(path / "images")
dls = ImageDataLoaders.from_name_func(path, files, label_func, item_tfms=Resize(224))
learn = timm_learner(dls, "efficientnet_b2", metrics=error_rate)

learn.fit_one_cycle(3, slice(0.001, 0.03))
```

**Comment by dreamflasher** [comment]
Sorry, my bad, I didn't realize that wwf and timm are seperate libraries, updated wwf and now it's working.

**Comment by muellerzr** [comment]
Great! Glad to see it's working now

**Comment by davecampbell** [comment]
i am using an offline copy of timm (0.3.4) and wwf (0.0.10) in a kaggle notebook, and just got this error.
it actually ran perfectly earlier today, and was able to do a submission from that notebook.

fairly green to all this, but wanted to use an efficientnet in fast.ai so was so glad i discovered wwf!

```
RuntimeError: running_mean should contain 3072 elements not 1536
```

**Comment by muellerzr** [comment]
@davecampbell what is your version of fastai? Looks like it's not the most recent version

**Comment by davecampbell** [comment]
whatever is on the kaggle containers, i suppose.
!pip freeze produced:
```
fastai==2.1.8
```

**Comment by muellerzr** [comment]
You need to update fastai as well, as that is outdated. This fix is for versions > 2.2.4 I _believe_. This library will always be updated to the latest fastai version, which Kaggle will not always be

**Comment by davecampbell** [comment]
that sounds reasonable - let me work on getting that fixed and will report back.  will also inform another fellow who said he had the same issue.
funky thing is that it actually ran error-free earlier today.
thanks so much for your attention.

**Comment by davecampbell** [comment]
i did load fastai 2.2.5 - but as it loaded, it said it was already there.
nonetheless, it ran after that - so i think that was the right advice!
thanks for that!
